version: "3"

services:
  db:
    image: mysql
    ports:
      - 3306:3306
    working_dir: "/workspace"
    volumes:
      - ".:/workspace"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: provoit
